### ISSUE TITLE
Thread Digest has undefined error

### ISSUE THREAD

**Issue by mendahu** [mendahu/off-nominal-discord-bot#168]

**Comment by mendahu** [comment]
2022-05-12T12:00:00.776758+00:00 app[worker.1]: /app/dist/clients/main/handlers/handleThreadDigestSend.js:70
2022-05-12T12:00:00.776767+00:00 app[worker.1]: thread: msgCollection.value.first().channel,
2022-05-12T12:00:00.776768+00:00 app[worker.1]: ^
2022-05-12T12:00:00.776769+00:00 app[worker.1]: 
2022-05-12T12:00:00.776769+00:00 app[worker.1]: TypeError: Cannot read properties of undefined (reading 'channel')
2022-05-12T12:00:00.776770+00:00 app[worker.1]: at /app/dist/clients/main/handlers/handleThreadDigestSend.js:70:64
2022-05-12T12:00:00.776770+00:00 app[worker.1]: at Array.map (<anonymous>)
2022-05-12T12:00:00.776771+00:00 app[worker.1]: at Client.<anonymous> (/app/dist/clients/main/handlers/handleThreadDigestSend.js:68:24)
2022-05-12T12:00:00.776772+00:00 app[worker.1]: at step (/app/dist/clients/main/handlers/handleThreadDigestSend.js:33:23)
2022-05-12T12:00:00.776772+00:00 app[worker.1]: at Object.next (/app/dist/clients/main/handlers/handleThreadDigestSend.js:14:53)
2022-05-12T12:00:00.776772+00:00 app[worker.1]: at fulfilled (/app/dist/clients/main/handlers/handleThreadDigestSend.js:5:58)
2022-05-12T12:00:00.776773+00:00 app[worker.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
